// Bitrix24 rules (@bitrix24/eslint-plugin-bitrix24-rules) and replacements of ESLint core rules (@bitrix24/core).
export const rules = {
	'@bitrix24/bitrix24-rules/no-io-without-polyfill': 'error',
	'@bitrix24/bitrix24-rules/no-pseudo-private': 'error',
	'@bitrix24/bitrix24-rules/no-native-events-binding': 'error',
	'@bitrix24/bitrix24-rules/no-typeof': 'error',
	'@bitrix24/bitrix24-rules/no-bx-message': 'error',
	'@bitrix24/bitrix24-rules/no-classlist': 'error',
	'@bitrix24/bitrix24-rules/no-style': 'error',
	'@bitrix24/bitrix24-rules/no-jsdd': 'error',
	'@bitrix24/bitrix24-rules/no-native-dialogs': 'error',
	'@bitrix24/bitrix24-rules/no-native-dom-methods': 'error',
	'@bitrix24/bitrix24-rules/no-eventemitter-without-namespace': 'error',
	'@bitrix24/bitrix24-rules/no-bx': 'error',
	'@bitrix24/bitrix24-rules/need-alias': 'warn',
	'@bitrix24/bitrix24-rules/sort-imports': 'warn',
	'@bitrix24/bitrix24-rules/prefer-inline-type-imports': 'warn',
	'@bitrix24/bitrix24-rules/brace-on-same-line': [
		'error',
		{
			FunctionExpression: 'ignore',
			FunctionDeclaration: 'never',
			ArrowFunctionExpression: 'always',
			IfStatement: 'never',
			TryStatement: 'never',
			DoWhileStatement: 'never',
			WhileStatement: 'never',
			WithStatement: 'never',
			ForStatement: 'never',
			ForInStatement: 'never',
			ForOfStatement: 'never',
			SwitchStatement: 'never',
			ClassDeclaration: 'never',
			MethodDeclaration: 'never',
			ExportClass: 'never',
			ExportClassAnon: 'never',
			ExportFunctionAnon: 'never',
		},
	],
};
