// ECMAScript 6+.
export const rules = {
	'constructor-super': 'error',
	'no-class-assign': 'error',
	'no-const-assign': 'error',
	'no-dupe-class-members': 'error',
	'no-new-native-nonconstructor': 'error',
	'no-restricted-exports': ['error', { restrictedNamedExports: ['default', 'then'] }],
	'no-this-before-super': 'error',
	'no-useless-computed-key': 'error',
	'no-useless-constructor': 'error',
	'no-useless-rename': [
		'error',
		{
			ignoreDestructuring: false,
			ignoreImport: false,
			ignoreExport: false,
		},
	],
	'no-var': 'error',
	'object-shorthand': ['error', 'always', { ignoreConstructors: false, avoidQuotes: true }],
	'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
	'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: true }],
	'prefer-numeric-literals': 'error',
	'prefer-rest-params': 'error',
	'prefer-spread': 'error',
	'prefer-template': 'error',
	'require-yield': 'error',
	'symbol-description': 'error',
	'no-template-curly-in-string': 'warn',
};
