// Formatting. Implemented by @stylistic rules bundled into dist/stylistic.js.
export const rules = {
	'@stylistic/no-extra-semi': 'error',
	'@stylistic/dot-location': ['error', 'property'],
	'@stylistic/no-floating-decimal': 'error',
	'@stylistic/no-multi-spaces': ['error', { ignoreEOLComments: false }],
	'@stylistic/wrap-iife': ['error', 'any', { functionPrototypeMethods: false }],
	'@stylistic/arrow-parens': 'warn',
	'@stylistic/arrow-spacing': ['error', { before: true, after: true }],
	'@stylistic/generator-star-spacing': ['error', { before: false, after: true }],
	'@stylistic/no-confusing-arrow': ['error', { allowParens: true }],
	'@stylistic/rest-spread-spacing': ['error', 'never'],
	'@stylistic/template-curly-spacing': 'error',
	'@stylistic/yield-star-spacing': ['error', 'after'],
	'@stylistic/array-bracket-spacing': ['error', 'never'],
	'@stylistic/block-spacing': ['error', 'always'],
	'@stylistic/comma-dangle': [
		'error',
		{
			arrays: 'always-multiline',
			objects: 'always-multiline',
			imports: 'always-multiline',
			exports: 'always-multiline',
			functions: 'always-multiline',
		},
	],
	'@stylistic/comma-spacing': ['error', { before: false, after: true }],
	'@stylistic/comma-style': [
		'error',
		'last',
		{
			exceptions: {
				ArrayExpression: false,
				ArrayPattern: false,
				ArrowFunctionExpression: false,
				CallExpression: false,
				FunctionDeclaration: false,
				FunctionExpression: false,
				ImportDeclaration: false,
				ObjectExpression: false,
				ObjectPattern: false,
				VariableDeclaration: false,
				NewExpression: false,
			},
		},
	],
	'@stylistic/computed-property-spacing': ['error', 'never'],
	'@stylistic/eol-last': ['error', 'always'],
	'@stylistic/function-call-argument-newline': ['error', 'consistent'],
	'@stylistic/function-call-spacing': ['error', 'never'],
	'@stylistic/function-paren-newline': ['error', 'multiline-arguments'],
	'@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
	'@stylistic/indent': [
		'error',
		'tab',
		{
			SwitchCase: 1,
			VariableDeclarator: 1,
			outerIIFEBody: 'off',
			FunctionDeclaration: { parameters: 1, body: 1 },
			FunctionExpression: { parameters: 1, body: 1 },
			CallExpression: { arguments: 1 },
			ArrayExpression: 1,
			ObjectExpression: 1,
			ImportDeclaration: 1,
			flatTernaryExpressions: false,
			ignoreComments: false,
			ignoredNodes: ['TemplateLiteral *'],
		},
	],
	'@stylistic/key-spacing': ['error', { beforeColon: false, afterColon: true }],
	'@stylistic/keyword-spacing': [
		'error',
		{
			before: true,
			after: true,
			overrides: {
				return: { after: true },
				throw: { after: true },
				case: { after: true },
			},
		},
	],
	'@stylistic/linebreak-style': ['error', 'unix'],
	'@stylistic/lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
	'@stylistic/max-len': [
		'error',
		120,
		2,
		{
			ignoreUrls: true,
			ignoreComments: false,
			ignoreRegExpLiterals: true,
			ignoreStrings: true,
			ignoreTemplateLiterals: true,
		},
	],
	'@stylistic/new-parens': 'error',
	'@stylistic/newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],
	'@stylistic/no-mixed-operators': [
		'error',
		{
			groups: [
				['%', '**'],
				['%', '+'],
				['%', '-'],
				['%', '*'],
				['%', '/'],
				['/', '*'],
				['&', '|', '<<', '>>', '>>>'],
				['==', '!=', '===', '!=='],
				['&&', '||'],
			],
			allowSamePrecedence: true,
		},
	],
	'@stylistic/no-mixed-spaces-and-tabs': 'error',
	'@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
	'@stylistic/no-trailing-spaces': ['error', { skipBlankLines: false, ignoreComments: false }],
	'@stylistic/no-whitespace-before-property': 'error',
	'@stylistic/nonblock-statement-body-position': ['error', 'below', { overrides: {} }],
	'@stylistic/object-curly-spacing': ['error', 'always'],
	'@stylistic/object-curly-newline': [
		'error',
		{
			ObjectExpression: { multiline: true, consistent: true },
			ObjectPattern: { multiline: true, consistent: true },
			ImportDeclaration: { multiline: true, consistent: true },
			ExportDeclaration: { multiline: true, consistent: true },
		},
	],
	'@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
	'@stylistic/one-var-declaration-per-line': ['error', 'always'],
	'@stylistic/operator-linebreak': ['error', 'before', { overrides: { '=': 'none' } }],
	'@stylistic/padded-blocks': [
		'error',
		{ blocks: 'never', classes: 'never', switches: 'never' },
		{ allowSingleLineBlocks: true },
	],
	'@stylistic/padding-line-between-statements': [
		'error',
		{ blankLine: 'always', prev: '*', next: 'return' },
		{ blankLine: 'always', prev: 'block-like', next: 'block-like' },
	],
	'@stylistic/quote-props': ['error', 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
	'@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
	'@stylistic/semi': ['error', 'always'],
	'@stylistic/semi-spacing': ['error', { before: false, after: true }],
	'@stylistic/space-before-blocks': 'error',
	'@stylistic/space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
	'@stylistic/space-in-parens': ['error', 'never'],
	'@stylistic/space-infix-ops': 'error',
	'@stylistic/space-unary-ops': ['error', { words: true, nonwords: false, overrides: {} }],
	'@stylistic/spaced-comment': [
		'error',
		'always',
		{
			line: { exceptions: ['-', '+'], markers: ['=', '!', '/'] },
			block: {
				exceptions: ['-', '+'],
				markers: ['=', '!', ':', '::'],
				balanced: true,
			},
		},
	],
	'@stylistic/switch-colon-spacing': ['error', { after: true, before: false }],
	'@stylistic/template-tag-spacing': ['error', 'never'],
};
