// eslint-plugin-vue, bundled (@bitrix24/vue). No native oxlint vue rule is used: they do not
// recognize the components of .js and .ts files that Bitrix24 marks with `// @vue/component`
// (2,400 in the modules repository). plugins/vue-components.js also makes the bundled rules
// recognize components by their shape and by the factory they are passed to.
export const rules = {
	'@bitrix24/vue/no-arrow-functions-in-watch': 'error',
	'@bitrix24/vue/no-async-in-computed-properties': 'error',
	'@bitrix24/vue/no-computed-properties-in-data': 'error',
	'@bitrix24/vue/no-deprecated-data-object-declaration': 'error',
	'@bitrix24/vue/no-deprecated-events-api': 'error',
	'@bitrix24/vue/no-deprecated-props-default-this': 'error',
	'@bitrix24/vue/no-deprecated-vue-config-keycodes': 'error',
	'@bitrix24/vue/no-dupe-keys': 'error',
	'@bitrix24/vue/no-expose-after-await': 'error',
	'@bitrix24/vue/no-lifecycle-after-await': 'error',
	'@bitrix24/vue/no-reserved-component-names': 'error',
	'@bitrix24/vue/no-reserved-keys': 'error',
	'@bitrix24/vue/no-reserved-props': 'error',
	'@bitrix24/vue/no-shared-component-data': 'error',
	'@bitrix24/vue/no-side-effects-in-computed-properties': 'error',
	'@bitrix24/vue/no-watch-after-await': 'error',
	'@bitrix24/vue/prefer-import-from-vue': 'error',
	'@bitrix24/vue/require-render-return': 'error',
	'@bitrix24/vue/require-slots-as-functions': 'error',
	'@bitrix24/vue/return-in-computed-property': 'error',
	'@bitrix24/vue/return-in-emits-validator': 'error',
	'@bitrix24/vue/valid-define-emits': 'error',
	'@bitrix24/vue/valid-define-props': 'error',
	'@bitrix24/vue/valid-next-tick': 'error',
	'@bitrix24/vue/prop-name-casing': 'warn',
	'@bitrix24/vue/require-default-prop': 'warn',
	'@bitrix24/vue/no-multiple-slot-args': 'warn',
	'@bitrix24/vue/multi-word-component-names': 'error',
	'@bitrix24/vue/no-deprecated-destroyed-lifecycle': 'error',
	'@bitrix24/vue/no-deprecated-dollar-listeners-api': 'error',
	'@bitrix24/vue/no-deprecated-dollar-scopedslots-api': 'error',
	'@bitrix24/vue/no-deprecated-filter': 'error',
	'@bitrix24/vue/no-mutating-props': 'error',
	'@bitrix24/vue/no-ref-as-operand': 'error',
	'@bitrix24/vue/no-setup-props-reactivity-loss': 'error',
	'@bitrix24/vue/no-use-computed-property-like-method': 'error',
	'@bitrix24/vue/require-prop-type-constructor': 'error',
	'@bitrix24/vue/require-valid-default-prop': 'error',
	'@bitrix24/vue/one-component-per-file': 'warn',
	'@bitrix24/vue/require-explicit-emits': 'warn',
	'@bitrix24/vue/require-prop-types': 'warn',
	'@bitrix24/vue/order-in-components': 'warn',
};
