// eslint-plugin-vue: native oxlint rules first, bundled JS rules (@bitrix24/vue) where oxlint has none
// or where the native rule does not recognize components declared in .js files.
export const rules = {
	'vue/no-arrow-functions-in-watch': 'error',
	'vue/no-async-in-computed-properties': 'error',
	'vue/no-computed-properties-in-data': 'error',
	'vue/no-deprecated-data-object-declaration': 'error',
	'vue/no-deprecated-events-api': 'error',
	'vue/no-deprecated-props-default-this': 'error',
	'vue/no-deprecated-vue-config-keycodes': 'error',
	'vue/no-dupe-keys': 'error',
	'vue/no-expose-after-await': 'error',
	'vue/no-lifecycle-after-await': 'error',
	'vue/no-reserved-component-names': 'error',
	'vue/no-reserved-keys': 'error',
	'vue/no-reserved-props': 'error',
	'vue/no-shared-component-data': 'error',
	'vue/no-side-effects-in-computed-properties': 'error',
	'vue/no-watch-after-await': 'error',
	'vue/prefer-import-from-vue': 'error',
	'vue/require-render-return': 'error',
	'vue/require-slots-as-functions': 'error',
	'vue/return-in-computed-property': 'error',
	'vue/return-in-emits-validator': 'error',
	'vue/valid-define-emits': 'error',
	'vue/valid-define-props': 'error',
	'vue/valid-next-tick': 'error',
	'vue/prop-name-casing': 'warn',
	'vue/require-default-prop': 'warn',
	'vue/no-multiple-slot-args': 'warn',
	'@bitrix24/vue/multi-word-component-names': 'error',
	'@bitrix24/vue/no-deprecated-destroyed-lifecycle': 'error',
	'@bitrix24/vue/no-deprecated-dollar-listeners-api': 'error',
	'@bitrix24/vue/no-deprecated-dollar-scopedslots-api': 'error',
	'@bitrix24/vue/no-deprecated-filter': 'error',
	'@bitrix24/vue/no-mutating-props': 'error',
	'@bitrix24/vue/no-ref-as-operand': 'error',
	'@bitrix24/vue/no-setup-props-reactivity-loss': 'error',
	'@bitrix24/vue/no-use-computed-property-like-method': 'error',
	'@bitrix24/vue/require-prop-type-constructor': 'error',
	'@bitrix24/vue/require-valid-default-prop': 'error',
	'@bitrix24/vue/one-component-per-file': 'warn',
	'@bitrix24/vue/require-explicit-emits': 'warn',
	'@bitrix24/vue/require-prop-types': 'warn',
	'@bitrix24/vue/order-in-components': 'warn',
};
