// Script rules — work in .js/.ts files (Options API, Composition API, JSX).
// SFC-specific rules are disabled — consumers using .vue files should
// re-enable them scoped to files: ['**/*.vue'] in their config.
export const rules = {
	// Script rules
	'vue/jsx-uses-vars': 'error',
	'vue/multi-word-component-names': 'error',
	'vue/no-arrow-functions-in-watch': 'error',
	'vue/no-async-in-computed-properties': 'error',
	'vue/no-computed-properties-in-data': 'error',
	'vue/no-deprecated-data-object-declaration': 'error',
	'vue/no-deprecated-destroyed-lifecycle': 'error',
	'vue/no-deprecated-dollar-listeners-api': 'error',
	'vue/no-deprecated-dollar-scopedslots-api': 'error',
	'vue/no-deprecated-events-api': 'error',
	'vue/no-deprecated-filter': 'error',
	'vue/no-deprecated-props-default-this': 'error',
	'vue/no-deprecated-vue-config-keycodes': 'error',
	'vue/no-dupe-keys': 'error',
	'vue/no-expose-after-await': 'error',
	'vue/no-lifecycle-after-await': 'error',
	'vue/no-mutating-props': 'error',
	'vue/no-ref-as-operand': 'error',
	'vue/no-reserved-component-names': 'error',
	'vue/no-reserved-keys': 'error',
	'vue/no-reserved-props': 'error',
	'vue/no-setup-props-reactivity-loss': 'error',
	'vue/no-shared-component-data': 'error',
	'vue/no-side-effects-in-computed-properties': 'error',
	'vue/no-use-computed-property-like-method': 'error',
	'vue/no-watch-after-await': 'error',
	'vue/prefer-import-from-vue': 'error',
	'vue/require-prop-type-constructor': 'error',
	'vue/require-render-return': 'error',
	'vue/require-slots-as-functions': 'error',
	'vue/require-valid-default-prop': 'error',
	'vue/return-in-computed-property': 'error',
	'vue/return-in-emits-validator': 'error',
	'vue/valid-define-emits': 'error',
	'vue/valid-define-props': 'error',
	'vue/valid-next-tick': 'error',
	'vue/one-component-per-file': 'warn',
	'vue/prop-name-casing': 'warn',
	'vue/require-default-prop': 'warn',
	'vue/require-explicit-emits': 'warn',
	'vue/require-prop-types': 'warn',
	'vue/no-multiple-slot-args': 'warn',
	'vue/order-in-components': 'warn',

	// Bitrix24 overrides
	'vue/component-definition-name-casing': 'off',

	// SFC-only rules — require vue-parser, apply only to .vue files.
	// Disabled by default. Consumers should re-enable these scoped
	// to files: ['**/*.vue'] in their eslint config.
	'vue/comment-directive': 'off',
	'vue/no-child-content': 'off',
	'vue/no-deprecated-functional-template': 'off',
	'vue/no-deprecated-html-element-is': 'off',
	'vue/no-deprecated-inline-template': 'off',
	'vue/no-deprecated-router-link-tag-prop': 'off',
	'vue/no-deprecated-scope-attribute': 'off',
	'vue/no-deprecated-slot-attribute': 'off',
	'vue/no-deprecated-slot-scope-attribute': 'off',
	'vue/no-deprecated-v-bind-sync': 'off',
	'vue/no-deprecated-v-is': 'off',
	'vue/no-deprecated-v-on-native-modifier': 'off',
	'vue/no-deprecated-v-on-number-modifiers': 'off',
	'vue/no-dupe-v-else-if': 'off',
	'vue/no-duplicate-attributes': 'off',
	'vue/no-export-in-script-setup': 'off',
	'vue/no-parsing-error': 'off',
	'vue/no-template-key': 'off',
	'vue/no-textarea-mustache': 'off',
	'vue/no-unused-components': 'off',
	'vue/no-unused-vars': 'off',
	'vue/no-use-v-if-with-v-for': 'off',
	'vue/no-useless-template-attributes': 'off',
	'vue/no-v-for-template-key-on-child': 'off',
	'vue/no-v-text-v-html-on-component': 'off',
	'vue/require-component-is': 'off',
	'vue/require-toggle-inside-transition': 'off',
	'vue/require-v-for-key': 'off',
	'vue/use-v-on-exact': 'off',
	'vue/valid-attribute-name': 'off',
	'vue/valid-template-root': 'off',
	'vue/valid-v-bind': 'off',
	'vue/valid-v-cloak': 'off',
	'vue/valid-v-else': 'off',
	'vue/valid-v-else-if': 'off',
	'vue/valid-v-for': 'off',
	'vue/valid-v-html': 'off',
	'vue/valid-v-if': 'off',
	'vue/valid-v-is': 'off',
	'vue/valid-v-memo': 'off',
	'vue/valid-v-model': 'off',
	'vue/valid-v-on': 'off',
	'vue/valid-v-once': 'off',
	'vue/valid-v-pre': 'off',
	'vue/valid-v-show': 'off',
	'vue/valid-v-slot': 'off',
	'vue/valid-v-text': 'off',
	'vue/attribute-hyphenation': 'off',
	'vue/first-attribute-linebreak': 'off',
	'vue/html-closing-bracket-newline': 'off',
	'vue/html-closing-bracket-spacing': 'off',
	'vue/html-end-tags': 'off',
	'vue/html-indent': 'off',
	'vue/html-quotes': 'off',
	'vue/html-self-closing': 'off',
	'vue/max-attributes-per-line': 'off',
	'vue/multiline-html-element-content-newline': 'off',
	'vue/mustache-interpolation-spacing': 'off',
	'vue/no-multi-spaces': 'off',
	'vue/no-spaces-around-equal-signs-in-attribute': 'off',
	'vue/no-template-shadow': 'off',
	'vue/singleline-html-element-content-newline': 'off',
	'vue/v-bind-style': 'off',
	'vue/v-on-event-hyphenation': 'off',
	'vue/v-on-style': 'off',
	'vue/v-slot-style': 'off',
	'vue/attributes-order': 'off',
	'vue/block-order': 'off',
	'vue/no-lone-template': 'off',
	'vue/no-v-html': 'off',
	'vue/this-in-template': 'off',
};
